# Generated by Django 5.0.4 on 2026-08-07 12:21

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import journal.models
import journal.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('pdf', models.FileField(help_text='The typeset article (galley PDF).', upload_to='journal/articles/%Y/')),
                ('first_page', models.PositiveIntegerField(blank=True, null=True)),
                ('last_page', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=120, verbose_name='DOI')),
                ('licence', models.CharField(default='CC BY 4.0', help_text='The licence the article is published under.', max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['issue', 'first_page', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text="e.g. 'Editor-in-Chief', 'Associate Editor'.", max_length=150)),
                ('affiliation', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, max_length=30, verbose_name='ORCID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='journal/board/')),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Editorial Board Member',
                'verbose_name_plural': 'Editorial Board',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Journal of ELTAN (JELTAN)', max_length=200)),
                ('short_name', models.CharField(default='JELTAN', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('issn_online', models.CharField(blank=True, max_length=20, verbose_name='ISSN (online)')),
                ('issn_print', models.CharField(blank=True, max_length=20, verbose_name='ISSN (print)')),
                ('publisher', models.CharField(default='English Language Teachers Association of Nigeria', max_length=200)),
                ('aims_and_scope', ckeditor.fields.RichTextField(blank=True)),
                ('author_guidelines', ckeditor.fields.RichTextField(blank=True)),
                ('peer_review_policy', ckeditor.fields.RichTextField(blank=True)),
                ('publication_ethics', ckeditor.fields.RichTextField(blank=True, help_text='Malpractice statement, authorship, plagiarism, corrections and retractions.')),
                ('open_access_policy', ckeditor.fields.RichTextField(blank=True)),
                ('copyright_notice', ckeditor.fields.RichTextField(blank=True)),
                ('apc_amount', models.DecimalField(decimal_places=2, default=0, help_text='Charged to the corresponding author once an article is accepted. Set to 0 to waive it.', max_digits=10, verbose_name='Article processing charge')),
                ('apc_currency', models.CharField(default='NGN', max_length=10)),
                ('review_days', models.PositiveIntegerField(default=28, help_text='Days a reviewer is given to return a report, by default.')),
                ('reviews_required', models.PositiveIntegerField(default=2, help_text='Completed reviews an editor is advised to have before deciding.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journal/covers/')),
                ('is_accepting_submissions', models.BooleanField(default=True, help_text='Untick to close submissions — the submit form then explains that the journal is closed.')),
                ('closed_message', models.CharField(blank=True, default='JELTAN is not accepting new submissions at the moment. Please check back soon.', max_length=300)),
            ],
            options={
                'verbose_name': 'Journal Settings',
                'verbose_name_plural': 'Journal Settings',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('peer_reviewed', models.BooleanField(default=True, help_text='Untick for sections that are editor-reviewed only, e.g. book reviews or editorials.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, max_length=30, verbose_name='ORCID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='journal.article')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, help_text='Optional theme, e.g. "Special Issue on Multilingual Classrooms".', max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journal/issues/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-volume', '-number'],
                'unique_together': {('volume', 'number')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='Leave blank to publish online first, ahead of an issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.issue'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.section'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manuscript_id', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(help_text='250 words or fewer.')),
                ('keywords', models.CharField(help_text='Comma separated, 3–6 keywords.', max_length=300)),
                ('cover_letter', models.TextField(blank=True)),
                ('is_original_work', models.BooleanField(default=False)),
                ('not_under_review_elsewhere', models.BooleanField(default=False)),
                ('agrees_to_policies', models.BooleanField(default=False)),
                ('conflict_of_interest', models.TextField(blank=True, help_text="Any competing interests, or 'None'.")),
                ('funding_statement', models.TextField(blank=True)),
                ('ethics_statement', models.TextField(blank=True, help_text='Ethical approval and informed consent, where human participants were involved.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted — awaiting desk check'), ('under_review', 'Under peer review'), ('minor_revision', 'Minor revisions requested'), ('major_revision', 'Major revisions requested'), ('resubmitted', 'Revision submitted — awaiting editor'), ('accepted', 'Accepted'), ('in_production', 'In production'), ('published', 'Published'), ('desk_rejected', 'Desk rejected'), ('rejected', 'Rejected after review'), ('withdrawn', 'Withdrawn by author')], db_index=True, default='submitted', max_length=30)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('apc_status', models.CharField(choices=[('not_applicable', 'Not applicable yet'), ('pending', 'Awaiting payment'), ('paid', 'Paid'), ('waived', 'Waived')], default='not_applicable', max_length=20)),
                ('apc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('apc_reference', models.CharField(blank=True, max_length=100)),
                ('apc_paid_at', models.DateTimeField(blank=True, null=True)),
                ('handling_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_handled_submissions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='journal.section')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('reviewer_name', models.CharField(max_length=200)),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('reviewer_affiliation', models.CharField(blank=True, max_length=300)),
                ('token', models.CharField(default=journal.models.generate_review_token, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('invited', 'Invited — awaiting response'), ('accepted', 'Accepted — review in progress'), ('declined', 'Declined'), ('submitted', 'Review submitted'), ('cancelled', 'Cancelled by editor')], db_index=True, default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Accept as is'), ('minor_revision', 'Accept after minor revisions'), ('major_revision', 'Major revisions required, then re-review'), ('reject', 'Reject')], max_length=20)),
                ('comments_to_author', models.TextField(blank=True)),
                ('confidential_comments', models.TextField(blank=True, help_text='Seen by the editors only — never sent to the author.')),
                ('rating_originality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_methodology', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_clarity', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_relevance', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='journal.submission')),
            ],
            options={
                'verbose_name': 'Review Assignment',
                'ordering': ['round', 'invited_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('decision', models.CharField(choices=[('send_for_review', 'Send for peer review'), ('desk_reject', 'Desk reject (out of scope / below threshold)'), ('minor_revision', 'Minor revisions required'), ('major_revision', 'Major revisions required'), ('accept', 'Accept'), ('reject', 'Reject')], max_length=30)),
                ('letter_to_author', models.TextField(blank=True, help_text='Sent to the corresponding author as the decision letter.')),
                ('share_reviews_with_author', models.BooleanField(default=True, help_text="Include the reviewers' comments to the author in the decision email.")),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='journal.submission')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='submission',
            field=models.OneToOneField(blank=True, help_text='The manuscript this was published from. Blank for back issues loaded by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='journal.submission'),
        ),
        migrations.CreateModel(
            name='SubmissionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('orcid', models.CharField(blank=True, max_length=30, verbose_name='ORCID')),
                ('is_corresponding', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='journal.submission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('round', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the author sees this entry on their submission page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='journal.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('anonymised_manuscript', 'Anonymised manuscript'), ('title_page', 'Title page (with author details)'), ('supplementary', 'Supplementary material'), ('response_to_reviewers', 'Response to reviewers'), ('review_attachment', 'Reviewer attachment'), ('production', 'Production / proof')], max_length=30)),
                ('file', models.FileField(storage=journal.storage.private_storage, upload_to='submissions/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('round', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='journal.submission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round', 'kind', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor_in_chief', 'Editor-in-Chief'), ('managing_editor', 'Managing Editor'), ('editor', 'Section / Handling Editor')], default='editor', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Editor',
                'verbose_name_plural': 'Journal Editors',
                'ordering': ['role', 'user__last_name'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
