# Generated by Django 5.0.4 on 2026-08-08 11:27

import django.db.models.deletion
import journal.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted — awaiting administrative screening'), ('returned', 'Returned to author for correction'), ('editorial_screening', 'Passed screening — awaiting editorial decision'), ('under_review', 'Under peer review'), ('minor_revision', 'Minor revisions requested'), ('major_revision', 'Major revisions requested'), ('resubmitted', 'Revision submitted — awaiting editor'), ('accepted', 'Accepted'), ('in_production', 'In production — copyediting'), ('proof_review', 'Proof with the author'), ('proof_approved', 'Proof approved — ready to publish'), ('published', 'Published'), ('desk_rejected', 'Desk rejected'), ('rejected', 'Rejected after review'), ('withdrawn', 'Withdrawn by author')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(storage=journal.storage.private_storage, upload_to='proofs/%Y/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'With the author'), ('approved', 'Approved by the author'), ('corrections_requested', 'Corrections requested'), ('superseded', 'Superseded by a later proof')], default='sent', max_length=25)),
                ('note_to_author', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, help_text='Proofs are usually returned within a few days.', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('corrections', models.TextField(blank=True, help_text="The author's corrections, in their words.")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='journal.submission')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1)),
                ('files_complete', models.BooleanField(default=False)),
                ('is_anonymised', models.BooleanField(default=False)),
                ('title_page_separate', models.BooleanField(default=False)),
                ('abstract_and_keywords', models.BooleanField(default=False)),
                ('declarations_complete', models.BooleanField(default=False)),
                ('references_formatted', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('notes_to_author', models.TextField(blank=True, help_text='What the author must put right. Sent to them when the manuscript is returned.')),
                ('internal_notes', models.TextField(blank=True, help_text='Editorial office only.')),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_reports', to='journal.submission')),
            ],
            options={
                'verbose_name': 'Screening Report',
                'ordering': ['-screened_at'],
            },
        ),
    ]
