# Generated by Django 5.0.4 on 2026-08-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_submission_status_proof_screeningreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialdecision',
            name='decision',
            field=models.CharField(choices=[('send_for_review', 'Send for peer review'), ('another_round', 'Send the revision back for another review round'), ('return_to_author', 'Return to the author for correction (not a rejection)'), ('desk_reject', 'Desk reject (out of scope / below threshold)'), ('minor_revision', 'Minor revisions required'), ('major_revision', 'Major revisions required'), ('accept_with_changes', 'Accept subject to the changes listed in the letter'), ('accept', 'Accept'), ('reject_resubmit', 'Reject, but a resubmission would be welcome'), ('reject', 'Reject'), ('withdraw', 'Withdraw the manuscript')], max_length=30),
        ),
    ]
