# Generated by Django 5.0.4 on 2026-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_article_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='import_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
