# Generated by Django 5.0.4 on 2026-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_article_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_html',
            field=models.TextField(blank=True, help_text='Generated from the source manuscript. Editing it here does not change the PDF.'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_file',
            field=models.FileField(blank=True, help_text='The manuscript as supplied (.docx or .pdf). Kept so the article can be re-typeset.', upload_to='journal/sources/%Y/'),
        ),
        migrations.AddField(
            model_name='article',
            name='typeset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='typeset_note',
            field=models.CharField(blank=True, help_text='What the last typesetting run did, or why it could not.', max_length=300),
        ),
    ]
