# Generated by Django 5.0.4 on 2026-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_utf8mb4'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='typeset_mode',
            field=models.CharField(choices=[('auto', 'Automatic — re-set in JELTAN type when the text reads cleanly'), ('jeltan', 'Always re-set in JELTAN type'), ('original', "Keep the author's own pages behind a JELTAN cover")], default='auto', help_text="How a supplied PDF is handled. Word manuscripts are always set in the journal's type. Choose 'Keep the author's own pages' only when re-setting loses something the article needs, such as equations or complex tables.", max_length=10),
        ),
    ]
