# Generated by Django 5.0.4 on 2026-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_article_typeset_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalsettings',
            name='title_acronyms',
            field=models.TextField(blank=True, help_text='Extra acronyms to keep capitalised in article titles, separated by commas or new lines — for example: NELFA, SUBEB, ALTEN. Common ones (ELT, ESL, WAEC, JAMB, ICT, UNESCO…) are already known. Spell each one exactly as it should be printed.', verbose_name='Acronyms in titles'),
        ),
    ]
