# Generated by Django 5.0.4 on 2024-04-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'ELTAN Users'},
        ),
    ]
