# Generated by Django 5.0.4 on 2024-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Select Gender', 'Select Gender'), ('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
    ]
