# Generated by Django 5.0.4 on 2025-01-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eltan_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
