# Generated by Django 5.0.4 on 2026-09-13 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_utf8mb4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impersonator_email', models.EmailField(blank=True, max_length=254)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, help_text='How the session ended: manual, expired, or logout.', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('impersonator', models.ForeignKey(blank=True, help_text='The staff member who borrowed the session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_started', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, help_text='The account that was impersonated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impersonation Log',
                'verbose_name_plural': 'Impersonation Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
