# Generated by Django 5.0.4 on 2025-10-24 10:46

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor.fields.RichTextField()),
                ('category', models.CharField(blank=True, help_text="e.g., 'Membership', 'Conferences', 'General'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('icon', models.CharField(help_text="Material icon name (e.g., 'workspace_premium', 'event', 'school')", max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Optional link to more information', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional illustration/image', upload_to='features/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to ELTAN', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Short description under the main title')),
                ('hero_cta_text', models.CharField(default='Get Started', help_text='Call-to-action button text', max_length=50)),
                ('hero_cta_link', models.CharField(default='/subscribe/', help_text='URL for the CTA button', max_length=200)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero background or illustration', upload_to='homepage/')),
                ('secondary_cta_text', models.CharField(blank=True, max_length=50)),
                ('secondary_cta_link', models.CharField(blank=True, max_length=200)),
                ('about_title', models.CharField(default='About ELTAN', max_length=200)),
                ('about_content', ckeditor.fields.RichTextField(blank=True)),
                ('about_image', models.ImageField(blank=True, upload_to='homepage/')),
                ('show_statistics', models.BooleanField(default=True)),
                ('show_features', models.BooleanField(default=True)),
                ('show_partners', models.BooleanField(default=True)),
                ('show_faq', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text='Override default icon with Material icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('icon', models.CharField(choices=[('people', 'People/Members'), ('event', 'Events'), ('school', 'Training'), ('workspace_premium', 'Certifications'), ('trending_up', 'Growth'), ('location_city', 'Chapters')], max_length=50)),
                ('number', models.CharField(help_text="e.g., '500+', '10K', '95%'", max_length=20)),
                ('label', models.CharField(help_text="e.g., 'Active Members', 'Annual Events'", max_length=100)),
                ('suffix', models.CharField(blank=True, help_text="e.g., '+', 'K', '%'", max_length=10)),
                ('color', models.CharField(default='#E67918', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Statistics',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text="e.g., 'ELTAN Member', 'Conference Attendee'", max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Member photo', upload_to='testimonials/')),
                ('rating', models.IntegerField(default=5, help_text='1-5 stars')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=200)),
                ('template', models.CharField(choices=[('default', 'Default Template'), ('full_width', 'Full Width'), ('sidebar', 'With Sidebar'), ('cards', 'Card Layout')], default='default', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('show_in_menu', models.BooleanField(default=False)),
                ('menu_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text Content'), ('image', 'Image'), ('video', 'Video'), ('cards', 'Card Grid'), ('stats', 'Statistics'), ('cta', 'Call to Action'), ('gallery', 'Image Gallery'), ('form', 'Form')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('css_classes', models.CharField(blank=True, help_text='Additional CSS classes', max_length=200)),
                ('background_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
