# Generated by Django 5.0.4 on 2025-10-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_faq_feature_homepage_partner_sociallink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='homepage_slides/')),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_link', models.CharField(blank=True, help_text='URL for the CTA button', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'abstract': False,
            },
        ),
    ]

