# Generated by Django 5.0.4 on 2025-12-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='alternate_email',
            field=models.EmailField(blank=True, help_text='Secondary contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Secondary phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2025 ELTAN. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_text',
            field=models.TextField(blank=True, help_text='Brief description for footer about section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_title',
            field=models.CharField(blank=True, default='About ELTAN', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Footer logo (optional, uses header logo if empty)', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_announcement',
            field=models.CharField(blank=True, help_text='Optional announcement bar text', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_description',
            field=models.TextField(blank=True, help_text='Newsletter signup description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_title',
            field=models.CharField(blank=True, default='Subscribe to Our Newsletter', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_hours',
            field=models.CharField(blank=True, help_text='e.g., Mon-Fri: 9AM-5PM', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_header_announcement',
            field=models.BooleanField(default=False, help_text='Show/hide announcement bar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact number', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main logo for header', upload_to='site/'),
        ),
    ]
