# Generated by Django 5.0.4 on 2025-12-29 08:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_header_footer_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='alternate_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_about_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_about_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_contact_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_announcement',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='newsletter_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='newsletter_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='office_hours',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_header_announcement',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content1_button_link',
            field=models.CharField(default='#features', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content1_button_text',
            field=models.CharField(default='Explore Benefits', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content1_description',
            field=ckeditor.fields.RichTextField(blank=True, default='Our membership provides unparalleled value through continuous learning, networking, and career development opportunities.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content1_subtitle',
            field=models.CharField(default='Professional Growth', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content1_title',
            field=models.CharField(default='Invest in Your Potential', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content2_button_link',
            field=models.CharField(default='/register/', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content2_button_text',
            field=models.CharField(default='Get Started', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content2_description',
            field=models.TextField(default='Join a community of ambitious professionals who are transforming their careers and making an impact in their industries. ELTAN members benefit from exclusive opportunities, connections, and resources that accelerate professional growth.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content2_subtitle',
            field=models.CharField(default='Community Impact', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content2_title',
            field=models.CharField(default='Boost Your Career Growth Today', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_link',
            field=models.CharField(default='/register/', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_button_text',
            field=models.CharField(default='Get Started Today', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_description',
            field=models.TextField(default='Join over 500 professionals who are accelerating their growth with ELTAN. Get access to exclusive events, training, and a powerful network.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_button_link',
            field=models.CharField(default='#contact', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_secondary_button_text',
            field=models.CharField(default='Contact Us', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_title',
            field=models.CharField(default='Ready to Transform Your Career?', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_subtitle',
            field=models.TextField(default='Have questions about our service, we offer wide-range of services to give the best service to the community.', help_text='Description under FAQ heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_title',
            field=models.CharField(default='Frequently Asked Questions', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_description',
            field=models.TextField(default="Join Nigeria's premier association for English language teachers. Access conferences, training, resources, and a vibrant community dedicated to excellence in English language teaching and learning.", help_text='Description under features heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_subtitle',
            field=models.CharField(default='What We Offer', help_text='Small text above features heading', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_title',
            field=models.CharField(default='Empowering English Language Teachers with Resources, Community & Professional Growth', help_text='Main features section heading', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_badge_text',
            field=models.CharField(default='Professional Membership Organization', help_text='Badge text above hero title', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Join us in fostering excellence in English language teaching and learning across Nigeria.', help_text='Short description under the main title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_cta_link',
            field=models.CharField(blank=True, default='#features', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='secondary_cta_text',
            field=models.CharField(blank=True, default='Learn More', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
    ]
