# Generated by Django 5.0.3 on 2024-03-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_sigs_alter_memberprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(choices=[('Associate', 'Associate'), ('Premium', 'Premium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='membership_type',
            field=models.CharField(choices=[('Associate', 'Associate'), ('Premium', 'Premium')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending')], max_length=20),
        ),
    ]
