# Generated by Django 5.0.3 on 2024-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_membershiptype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='sigs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sig_images/'),
        ),
    ]
