# Generated by Django 5.0.3 on 2024-04-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_events_alter_sigs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
