# Generated by Django 5.0.3 on 2024-04-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_events_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=60)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('featured_img', models.ImageField(blank=True, null=True, upload_to='news_imgaes/')),
            ],
        ),
    ]
