# Generated by Django 5.0.3 on 2024-04-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
