# Generated by Django 5.0.4 on 2024-04-12 21:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_news_short_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceregistration',
            options={'ordering': ['-registration_date'], 'verbose_name_plural': 'Conference Registrations'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-event_date'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='sigs',
            options={'verbose_name_plural': 'Sigs'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
