# Generated by Django 5.0.4 on 2024-04-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_alter_conferenceregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
