# Generated by Django 5.0.4 on 2024-04-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
