# Generated by Django 5.0.4 on 2024-04-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proof'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('pending', 'pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
