# Generated by Django 5.0.4 on 2024-04-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_subscription_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='membership_type',
            field=models.CharField(choices=[('Associate', 'Associate'), ('Associate I', 'Associate I')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proof/'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
