# Generated by Django 5.0.4 on 2024-04-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
