# Generated by Django 5.0.4 on 2024-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='membership_type',
            field=models.CharField(choices=[('New Membership', 'New Membership'), ('Renew Membership', 'Renew Membership')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_amount',
            field=models.DecimalField(choices=[('5,500', '5,500'), ('3,000', '3,000')], decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_proof',
            field=models.FileField(upload_to='payment_proof/', null=True, blank=True),
        ),
    ]
