# Generated by Django 5.0.4 on 2024-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_alter_subscription_membership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
