# Generated by Django 5.0.4 on 2024-05-10 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_alter_subscription_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='resources/')),
            ],
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(choices=[('New Membership (5,500)', 'New Membership (5,500)'), ('Renew Membership (3,000)', 'Renew Membership (3,000)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='membership_type',
            field=models.CharField(choices=[('New Membership (5,500)', 'New Membership (5,500)'), ('Renew Membership (3,000)', 'Renew Membership (3,000)')], max_length=50),
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.resource')),
            ],
            options={
                'verbose_name_plural': 'Downloads',
                'ordering': ['-download_date'],
            },
        ),
    ]
