# Generated by Django 5.0.4 on 2024-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_resource_alter_membershiptype_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['category'], 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('select', 'Select Gender'), ('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='membership_type',
            field=models.CharField(choices=[('select', 'Select Membership'), ('New Membership', 'New Membership (N5,500)'), ('Renew Membership', 'Renew Membership (N3,000)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
