# Generated by Django 5.0.4 on 2025-01-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0022_alter_memberprofile_state'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(choices=[('year 1', '2023/2024'), ('year 2', '2024/2025')], default='2024/2025', max_length=9),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='certificates/')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.subscription')),
            ],
        ),
    ]
