# Generated by Django 5.0.4 on 2025-01-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0023_subscription_eltan_year_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(default='2024/2025', max_length=9),
        ),
    ]
