# Generated by Django 5.0.4 on 2025-01-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0024_alter_subscription_eltan_year'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='subscription',
                    name='eltan_year',
                    field=models.CharField(max_length=9),
                ),
            ],
            database_operations=[],
        ),
    ]
