# Generated by Django 5.0.4 on 2025-01-08 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0025_sync_eltan_year_field'),
    ]

    operations = [
        migrations.RunSQL(
            # First check if table exists and drop if it does
            """
            DROP TABLE IF EXISTS membership_certificate;
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS membership_certificate;
            """
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='certificates/')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.subscription')),
            ],
            options={
                'db_table': 'membership_certificate',
            },
        ),
    ]
