# Generated by Django 5.0.4 on 2025-01-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0026_create_certificate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELTANYearSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eltan_year', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ELTAN Year Setting',
                'verbose_name_plural': 'ELTAN Year Settings',
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(default='2024/2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state_chapter',
            field=models.CharField(blank=True, choices=[('Select', 'Select State'), ('FCT', 'Abuja'), ('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKWA IBOM', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('GOOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOBE', 'Yobe'), ('ZAMFARA', 'Zamfara')], max_length=20, null=True),
        ),
    ]
