# Generated by Django 5.0.4 on 2025-01-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0027_eltanyearsetting_alter_subscription_eltan_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(choices=[('Select', 'Select Year'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='2024/2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='membership_type',
            field=models.CharField(choices=[('select', 'Select Membership'), ('New Membership', 'New Membership (N5,500)'), ('Renew Membership', 'Renew Membership (N3,000)')], default='New Membership (5,500)', max_length=50),
        ),
    ]
