# Generated by Django 5.0.4 on 2025-01-22 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0029_newsletter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EltanConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('registration_start', models.DateField(default=django.utils.timezone.now)),
                ('registration_end', models.DateField()),
                ('early_bird_end', models.DateField(blank=True, null=True)),
                ('member_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_early_bird_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_member_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('non_member_early_bird_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ELTAN Conference',
                'verbose_name_plural': 'ELTAN Conferences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(default='upload document', upload_to='conference_documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.eltanconference')),
            ],
        ),
        migrations.CreateModel(
            name='EltanConferenceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-Member')], max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='conference_payments/')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_presenting', models.BooleanField(default=False)),
                ('paper_title', models.CharField(blank=True, max_length=500, null=True)),
                ('paper_abstract', models.TextField(blank=True, null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.eltanconference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conference Registration',
                'verbose_name_plural': 'Conference Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('conference', 'user')},
            },
        ),
    ]
