# Generated by Django 5.0.4 on 2025-02-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0030_eltanconference_conferencedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eltan_conference_images/'),
        ),
    ]
