# Generated by Django 5.0.4 on 2025-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0032_conferencespeaker_conferenceschedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eltanconferenceregistration',
            old_name='payment_id',
            new_name='payment_reference',
        ),
        migrations.AddField(
            model_name='eltanconference',
            name='member_payment_link',
            field=models.URLField(blank=True, help_text='Paystack payment link for members', null=True),
        ),
        migrations.AddField(
            model_name='eltanconference',
            name='non_member_payment_link',
            field=models.URLField(blank=True, help_text='Paystack payment link for non-members', null=True),
        ),
        migrations.AlterField(
            model_name='eltanconferenceregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
