# Generated by Django 5.0.4 on 2025-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0034_alter_eltanconferenceregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
