# Generated by Django 5.0.4 on 2025-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0035_eltanconferenceregistration_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
