# Generated by Django 5.0.4 on 2025-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0036_eltanconferenceregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eltanconferenceregistration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
