# Generated by Django 5.0.4 on 2025-02-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0037_alter_eltanconferenceregistration_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eltanconferenceregistration',
            old_name='paystack_reference',
            new_name='paystack_ref',
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='eltanconferenceregistration',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
