# Generated by Django 5.0.4 on 2025-02-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0038_rename_paystack_reference_eltanconferenceregistration_paystack_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eltanconferenceregistration',
            name='registration_type',
            field=models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-Member')], default='non_member', max_length=20),
        ),
    ]
