# Generated by Django 5.0.4 on 2025-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0039_alter_eltanconferenceregistration_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconference',
            name='international_delegate_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='eltanconferenceregistration',
            name='registration_type',
            field=models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-Member (Nigeria)'), ('non_member2', 'Non-Member (International)')], default='non_member', max_length=20),
        ),
    ]
