# Generated by Django 5.0.4 on 2025-03-04 17:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0040_eltanconference_international_delegate_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencespeaker',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
