# Generated by Django 5.0.4 on 2025-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0041_alter_conferencespeaker_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eltanyearsetting',
            options={},
        ),
        migrations.AddField(
            model_name='eltanyearsetting',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eltanyearsetting',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='eltan_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(choices=[('Select', 'Select Year'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='2024/2025', max_length=9),
        ),
    ]
