# Generated by Django 5.0.4 on 2025-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0042_alter_eltanyearsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(choices=[('Select', 'Select Year'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2027-2028', '2027-2028')], default='2024/2025', max_length=9),
        ),
    ]
