# Generated by Django 5.0.4 on 2025-10-24 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0043_alter_subscription_eltan_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='sigs',
            options={'ordering': ['order', 'title'], 'verbose_name_plural': 'Sigs'},
        ),
        migrations.AddField(
            model_name='events',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='events',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for event cards', max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('announcement', 'Announcement'), ('event', 'Event'), ('member', 'Member News')], max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter_thumbnails/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, only members can download'),
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resource_thumbnails/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sigs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sigs',
            name='icon',
            field=models.CharField(blank=True, help_text='Material icon name for this SIG', max_length=50),
        ),
        migrations.AddField(
            model_name='sigs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sigs',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sigs',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sigs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('guide', 'Guides & Manuals'), ('template', 'Templates'), ('report', 'Reports'), ('presentation', 'Presentations'), ('policy', 'Policies'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='sigs',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
