# Generated by Django 5.0.4 on 2025-10-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0044_alter_resource_options_alter_sigs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'Manual Payment (Bank Transfer)'), ('paystack', 'Online Payment (Paystack)')], default='manual', help_text='Payment method used for this subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, null=True),
        ),
    ]
