# Generated by Django 5.0.4 on 2025-10-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0050_update_conference_and_loc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sigsregistration',
            options={'verbose_name': 'SIG Membership', 'verbose_name_plural': 'SIG Memberships'},
        ),
        migrations.AddField(
            model_name='sigs',
            name='moderator',
            field=models.ForeignKey(blank=True, help_text='SIG moderator assigned by admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_sigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sigsregistration',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='membership.sigs'),
        ),
        migrations.AlterField(
            model_name='sigsregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sig_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sigsregistration',
            unique_together={('user', 'sig')},
        ),
    ]
