# Generated by Django 5.0.4 on 2025-12-25 00:37

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0051_alter_sigsregistration_options_sigs_moderator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcoMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the executive member', max_length=200)),
                ('position', models.CharField(choices=[('president', 'President'), ('vice_president', 'National Vice President'), ('secretary', 'National Secretary'), ('assistant_secretary', 'Assistant National Secretary'), ('treasurer', 'Treasurer'), ('financial_secretary', 'Financial Secretary'), ('publicity_secretary', 'Publicity Secretary'), ('auditor', 'Auditor'), ('ex_officio', 'Ex-Officio'), ('legal_adviser', 'Legal Adviser'), ('provost', 'Provost'), ('other', 'Other Position')], help_text='Executive position/portfolio', max_length=50)),
                ('institution', models.CharField(blank=True, help_text='University, college, or organization', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin_url', models.URLField(blank=True, help_text='Full LinkedIn profile URL', verbose_name='LinkedIn Profile')),
                ('photo', models.ImageField(blank=True, help_text='Professional headshot (recommended: 400x400px)', null=True, upload_to='exco_members/')),
                ('bio', ckeditor.fields.RichTextField(blank=True, help_text='Brief biography or professional background')),
                ('start_date', models.DateField(help_text='Start date of this position')),
                ('end_date', models.DateField(blank=True, help_text='End date of position (leave blank for current members)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show in Current Exco section')),
                ('is_archived', models.BooleanField(default=False, help_text='Moved to Past Exco (archived members)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Link to existing ELTAN member account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exco_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Executive Committee Member',
                'verbose_name_plural': 'Executive Committee Members',
                'ordering': ['order', 'position', 'full_name'],
                'indexes': [models.Index(fields=['is_active', 'is_archived'], name='membership__is_acti_b6913d_idx'), models.Index(fields=['order'], name='membership__order_43d8f1_idx')],
            },
        ),
    ]
