# Generated by Django 5.0.4 on 2026-01-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0052_excomember'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='qualification_certificate',
            field=models.FileField(blank=True, help_text='Teaching qualification certificate for English language', null=True, upload_to='qualifications/'),
        ),
    ]
