# Generated by Django 5.0.4 on 2026-04-20 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0053_subscription_qualification_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconference',
            name='sponsor_packages',
            field=ckeditor.fields.RichTextField(blank=True, default='<h3>Sponsorship Categories</h3>\n<p>ELTAN offers four sponsorship tiers, each with a tailored package of recognition and benefits. Your sponsorship will not only support the success of this event but also offer your organisation meaningful visibility and engagement with a key audience.</p>\n\n<h4>1. Platinum Sponsor &ndash; &#8358;700,000 and above</h4>\n<ul>\n<li>Recognition as Platinum Sponsor in all event materials</li>\n<li>Logo placement on all banners, posters, and digital promotions</li>\n<li>Full-page advert in the conference programme</li>\n<li>Speaking opportunity during the opening session</li>\n<li>Exhibition booth in premium location</li>\n<li>4 complimentary registrations</li>\n<li>Social media recognition before, during, and after the event</li>\n<li>Company materials included in participant bags</li>\n</ul>\n\n<h4>2. Gold Sponsor &ndash; &#8358;500,000 &ndash; &#8358;699,000</h4>\n<ul>\n<li>Recognition as Gold Sponsor in event materials</li>\n<li>Logo on banners, posters, and digital promotions</li>\n<li>Half-page advert in the programme</li>\n<li>Exhibition booth</li>\n<li>2 complimentary registrations</li>\n<li>Social media shoutouts</li>\n<li>Company materials included in participant bags</li>\n</ul>\n\n<h4>3. Silver Sponsor &ndash; &#8358;350,000 &ndash; &#8358;499,000</h4>\n<ul>\n<li>Recognition as Silver Sponsor</li>\n<li>Logo on event website and select materials</li>\n<li>Quarter-page advert in the programme</li>\n<li>1 complimentary registration</li>\n<li>Shared exhibition space</li>\n<li>Mention on social media</li>\n</ul>\n\n<h4>4. Bronze Sponsor &ndash; &#8358;150,000 &ndash; &#8358;349,000</h4>\n<ul>\n<li>Name listed in the programme and on the website</li>\n<li>Company materials displayed at registration</li>\n<li>Mention during the closing session</li>\n</ul>\n\n<h3>In-Kind Sponsorship</h3>\n<p>ELTAN warmly welcomes contributions in forms other than cash. In-kind sponsors receive benefits matched to the value of their contribution, which may include logo display, exhibition space, and formal acknowledgements. Acceptable in-kind contributions include:</p>\n<ul>\n<li>Conference materials (e.g., bags, notepads, pens)</li>\n<li>Refreshments and catering</li>\n<li>Technical support (AV equipment, printing, photography)</li>\n</ul>\n<p>Custom sponsorship packages are also available upon request. We are happy to design an arrangement that aligns with your organisation&rsquo;s specific goals and budget.</p>', help_text='Sponsorship package tiers and benefits displayed on the Sponsors tab'),
        ),
    ]
