# Generated by Django 5.0.4 on 2026-04-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0054_add_sponsor_packages_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hotel or accommodation name', max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('distance_from_venue', models.CharField(blank=True, help_text='e.g. 5 mins walk, 2 km from venue', max_length=100)),
                ('price_range', models.CharField(blank=True, help_text='e.g. ₦15,000 – ₦30,000 / night', max_length=150)),
                ('room_types', models.CharField(blank=True, help_text='e.g. Standard, Deluxe, Suite', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('booking_deadline', models.DateField(blank=True, help_text='Last date for special/conference rates', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any special notes, booking codes, or additional details')),
                ('is_recommended', models.BooleanField(default=False, help_text='Mark as ELTAN recommended accommodation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conference_accommodation/')),
                ('order', models.IntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='membership.eltanconference')),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('inkind', 'In-Kind'), ('custom', 'Custom')], max_length=20)),
                ('tier_label', models.CharField(help_text='Display name, e.g. Platinum Sponsor', max_length=60)),
                ('price_range', models.CharField(help_text='e.g. ₦700,000+ or ₦500,000 – ₦699,000', max_length=120)),
                ('benefits', models.TextField(help_text='Enter one benefit per line. Each line becomes a bullet point on the frontend.')),
                ('is_featured', models.BooleanField(default=False, help_text="Shows a 'Most Inclusive' ribbon on the card")),
                ('cta_label', models.CharField(blank=True, help_text='Button text, e.g. Become a Platinum Sponsor', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_packages', to='membership.eltanconference')),
            ],
            options={
                'verbose_name': 'Sponsorship Package',
                'verbose_name_plural': 'Sponsorship Packages',
                'ordering': ['order'],
            },
        ),
    ]
