# Generated by Django 5.0.4 on 2026-04-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0057_alter_sponsor_packages_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='certificate_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin must approve the qualification certificate before the subscription becomes active', max_length=20),
        ),
    ]
