# Generated by Django 5.0.4 on 2026-06-22 08:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_ticket_ids(apps, schema_editor):
    """Issue ticket ids to already-completed registrations that lack one."""
    Registration = apps.get_model('membership', 'EltanConferenceRegistration')
    used = set(
        Registration.objects.exclude(ticket_id__isnull=True)
        .exclude(ticket_id='')
        .values_list('ticket_id', flat=True)
    )
    qs = Registration.objects.filter(payment_status='completed').filter(
        models.Q(ticket_id__isnull=True) | models.Q(ticket_id='')
    ).select_related('conference')
    for reg in qs:
        try:
            year = reg.conference.start_date.year
        except Exception:
            year = ''
        while True:
            candidate = f"ELTAN-{year}-{uuid.uuid4().hex[:6].upper()}"
            if candidate not in used:
                used.add(candidate)
                break
        reg.ticket_id = candidate
        reg.save(update_fields=['ticket_id'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0058_add_certificate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='ticket_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_conference_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(choices=[('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2027-2028', '2027-2028')], default='2024/2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='membership_type',
            field=models.CharField(choices=[('New Membership', 'New Membership (N5,500)'), ('Renew Membership', 'Renew Membership (N3,000)')], default='New Membership (5,500)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state_chapter',
            field=models.CharField(blank=True, choices=[('FCT', 'Abuja'), ('ABIA', 'Abia'), ('ADAMAWA', 'Adamawa'), ('AKWA IBOM', 'Akwa Ibom'), ('ANAMBRA', 'Anambra'), ('BAUCHI', 'Bauchi'), ('BAYELSA', 'Bayelsa'), ('BENUE', 'Benue'), ('BORNO', 'Borno'), ('CROSS RIVER', 'Cross River'), ('DELTA', 'Delta'), ('EBONYI', 'Ebonyi'), ('EDO', 'Edo'), ('EKITI', 'Ekiti'), ('ENUGU', 'Enugu'), ('GOOMBE', 'Gombe'), ('IMO', 'Imo'), ('JIGAWA', 'Jigawa'), ('KADUNA', 'Kaduna'), ('KANO', 'Kano'), ('KATSINA', 'Katsina'), ('KEBBI', 'Kebbi'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara'), ('LAGOS', 'Lagos'), ('NASARAWA', 'Nasarawa'), ('NIGER', 'Niger'), ('OGUN', 'Ogun'), ('ONDO', 'Ondo'), ('OSUN', 'Osun'), ('OYO', 'Oyo'), ('PLATEAU', 'Plateau'), ('RIVERS', 'Rivers'), ('SOKOTO', 'Sokoto'), ('TARABA', 'Taraba'), ('YOBE', 'Yobe'), ('ZAMFARA', 'Zamfara')], max_length=20, null=True),
        ),
        migrations.RunPython(backfill_ticket_ids, noop),
    ]
