# Generated by Django 5.0.4 on 2026-06-30 19:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0059_eltanconferenceregistration_payment_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconference',
            name='virtual_attendee_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('40000.00'), help_text='Flat rate for virtual attendees', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eltanconferenceregistration',
            name='registration_type',
            field=models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-Member (Nigeria)'), ('non_member2', 'Non-Member (International)'), ('virtual', 'Virtual Attendee')], default='non_member', max_length=20),
        ),
    ]
