# Generated by Django 5.0.4 on 2026-08-05 11:41
#
# Made re-runnable by hand: MySQL cannot roll back DDL, so a run of this
# migration that fails part-way leaves the columns/indexes it already created in
# place while django_migrations records nothing. Re-running then died with
# "Duplicate key name ..._eltan_year_..._uniq" (or "Duplicate column name").
#
# The schema changes that can already exist are therefore applied through
# introspection: each one is created only when it is actually missing. The model
# state Django tracks is unchanged, so the rest of the migration graph still
# lines up.

import re

import membership.models
from django.db import migrations, models

_YEAR_RE = re.compile(r'^(\d{4})\s*[-/]\s*(\d{4})$')


def _normalize(value):
    """'2024/2025' -> '2024-2025'; anything unrecognised is left alone."""
    if not value:
        return ''
    match = _YEAR_RE.match(str(value).strip())
    if not match:
        return str(value).strip()
    return f"{match.group(1)}-{match.group(2)}"


def _existing_columns(schema_editor, table):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return {
            column.name
            for column in connection.introspection.get_table_description(cursor, table)
        }


def _has_unique_on(schema_editor, table, column):
    """True when some UNIQUE constraint/index already covers exactly `column`."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table)
    return any(
        info.get('unique') and not info.get('primary_key') and info.get('columns') == [column]
        for info in constraints.values()
    )


def _add_missing_field(schema_editor, model, name, field, existing):
    if name in existing:
        return False
    field = field.clone()
    field.set_attributes_from_name(name)
    schema_editor.add_field(model, field)
    return True


def _ensure_unique_index(schema_editor, model, column):
    """Create the UNIQUE index on `column` only when nothing already enforces it.

    Deliberately raw DDL rather than schema_editor.alter_field(): on SQLite that
    rebuilds the table from the *historical* model, which silently drops columns
    added earlier in this same migration.
    """
    table = model._meta.db_table
    if _has_unique_on(schema_editor, table, column):
        return
    index_name = schema_editor._create_index_name(table, [column], suffix='_uniq')
    schema_editor.execute(
        'CREATE UNIQUE INDEX %s ON %s (%s)' % (
            schema_editor.quote_name(index_name),
            schema_editor.quote_name(table),
            schema_editor.quote_name(column),
        )
    )


def _dedupe_year_labels(year_setting):
    """Canonicalise year labels and drop exact duplicates.

    Has to happen before the UNIQUE index goes on: production may hold both
    '2024/2025' and '2024-2025', which are distinct strings today but become the
    same value the moment they are normalised. Nothing references these rows by
    key (subscriptions store the label as text), so dropping a duplicate config
    row is safe — the older row is kept.
    """
    seen = {}
    for setting in year_setting.objects.all().order_by('pk'):
        label = _normalize(setting.eltan_year)
        if label in seen:
            year_setting.objects.filter(pk=setting.pk).delete()
            continue
        seen[label] = setting.pk
        if label != setting.eltan_year:
            year_setting.objects.filter(pk=setting.pk).update(eltan_year=label)


def sync_schema(apps, schema_editor):
    registration = apps.get_model('membership', 'EltanConferenceRegistration')
    year_setting = apps.get_model('membership', 'ELTANYearSetting')

    reg_table = registration._meta.db_table
    reg_columns = _existing_columns(schema_editor, reg_table)
    _add_missing_field(
        schema_editor, registration, 'receipt_error',
        models.TextField(blank=True, default='', help_text='Why the last ticket/receipt email failed, if it did.'),
        reg_columns,
    )
    _add_missing_field(
        schema_editor, registration, 'receipt_sent_at',
        models.DateTimeField(blank=True, null=True, help_text='When the ticket/receipt email was last delivered successfully.'),
        reg_columns,
    )

    year_table = year_setting._meta.db_table
    year_columns = _existing_columns(schema_editor, year_table)
    _add_missing_field(
        schema_editor, year_setting, 'is_selectable',
        models.BooleanField(default=True, verbose_name='Selectable by members',
                            help_text='Untick to hide this year from the subscription form without deleting it.'),
        year_columns,
    )

    # eltan_year keeps max_length=20; the only schema change is the UNIQUE
    # constraint, which is exactly what a re-run collides on.
    _dedupe_year_labels(year_setting)
    _ensure_unique_index(schema_editor, year_setting, 'eltan_year')


def noop(apps, schema_editor):
    """Reverse is handled by the state operations; nothing to undo at DB level."""


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0060_eltanconference_virtual_attendee_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eltanyearsetting',
            options={'ordering': ['-eltan_year'], 'verbose_name': 'ELTAN Year', 'verbose_name_plural': 'ELTAN Years'},
        ),
        # These four are the ones a failed run can leave half-done, so their DDL
        # goes through sync_schema() while Django's state is updated as normal.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='eltanconferenceregistration',
                    name='receipt_error',
                    field=models.TextField(blank=True, default='', help_text='Why the last ticket/receipt email failed, if it did.'),
                ),
                migrations.AddField(
                    model_name='eltanconferenceregistration',
                    name='receipt_sent_at',
                    field=models.DateTimeField(blank=True, help_text='When the ticket/receipt email was last delivered successfully.', null=True),
                ),
                migrations.AddField(
                    model_name='eltanyearsetting',
                    name='is_selectable',
                    field=models.BooleanField(default=True, help_text='Untick to hide this year from the subscription form without deleting it.', verbose_name='Selectable by members'),
                ),
                migrations.AlterField(
                    model_name='eltanyearsetting',
                    name='eltan_year',
                    field=models.CharField(help_text='Format: 2026-2027 (two consecutive years).', max_length=20, unique=True, validators=[membership.models.validate_eltan_year]),
                ),
            ],
            database_operations=[
                migrations.RunPython(sync_schema, noop),
            ],
        ),
        # The rest only change null/blank/help_text/default or widen a column,
        # which every backend re-applies safely.
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank to use 31 August of the second year.', null=True),
        ),
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The year new subscriptions default to. Only one year can be current.', verbose_name='Current ELTAN year'),
        ),
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave blank to use 1 September of the first year.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
