# Generated by Django 5.0.4 on 2026-08-05 11:41

import membership.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0060_eltanconference_virtual_attendee_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eltanyearsetting',
            options={'ordering': ['-eltan_year'], 'verbose_name': 'ELTAN Year', 'verbose_name_plural': 'ELTAN Years'},
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='receipt_error',
            field=models.TextField(blank=True, default='', help_text='Why the last ticket/receipt email failed, if it did.'),
        ),
        migrations.AddField(
            model_name='eltanconferenceregistration',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket/receipt email was last delivered successfully.', null=True),
        ),
        migrations.AddField(
            model_name='eltanyearsetting',
            name='is_selectable',
            field=models.BooleanField(default=True, help_text='Untick to hide this year from the subscription form without deleting it.', verbose_name='Selectable by members'),
        ),
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='eltan_year',
            field=models.CharField(help_text='Format: 2026-2027 (two consecutive years).', max_length=20, unique=True, validators=[membership.models.validate_eltan_year]),
        ),
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank to use 31 August of the second year.', null=True),
        ),
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The year new subscriptions default to. Only one year can be current.', verbose_name='Current ELTAN year'),
        ),
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave blank to use 1 September of the first year.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='eltan_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
