# Generated by Django 5.0.4 on 2026-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0062_normalize_eltan_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eltanyearsetting',
            name='is_active',
            field=models.BooleanField(default=False, help_text='The year new subscriptions default to. Only one year can be current.', verbose_name='Current ELTAN year'),
        ),
    ]
