# Generated by Django 5.0.4 on 2026-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0063_alter_eltanyearsetting_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name as it should be printed, e.g. 'Dr. Kennedy Edegbe'.", max_length=200)),
                ('title', models.CharField(help_text="Title printed under the name, e.g. 'National President'.", max_length=120)),
                ('signature', models.ImageField(help_text='Signature image, ideally a transparent PNG on a white background. It is printed about 150x45pt, so a wide, short image works best.', upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to leave this signatory off newly generated certificates.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Print order — lower numbers appear first (president before secretary).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Signatory',
                'verbose_name_plural': 'Certificate Signatories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='receipt_error',
            field=models.TextField(blank=True, default='', help_text='Why the last receipt email failed, if it did.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription receipt was last emailed to the member.', null=True),
        ),
    ]
