# Generated by Django 5.0.4 on 2026-09-13 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0065_utf8mb4'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltanconference',
            name='certificate_name_baseline',
            field=models.FloatField(default=0.4690, help_text='Baseline the name sits on, as a fraction of page height measured from the top.'),
        ),
        migrations.AddField(
            model_name='eltanconference',
            name='certificate_name_font_size',
            field=models.FloatField(default=30, help_text="Point size for the participant's name on an A4 landscape certificate."),
        ),
        migrations.AddField(
            model_name='eltanconference',
            name='certificate_name_max_width',
            field=models.FloatField(default=0.5225, help_text='Widest the name may run, as a fraction of page width. Long names shrink to fit.'),
        ),
        migrations.AddField(
            model_name='eltanconference',
            name='certificate_name_x',
            field=models.FloatField(default=0.5005, help_text="Horizontal centre of the participant's name, as a fraction of page width (0.5 = centred)."),
        ),
        migrations.AddField(
            model_name='eltanconference',
            name='certificate_template',
            field=models.FileField(blank=True, help_text="Single-page PDF of the certificate artwork with the participant's name left blank. Leave empty to use the standard ELTAN certificate design.", null=True, upload_to='certificate_templates/'),
        ),
        migrations.AddField(
            model_name='eltanconference',
            name='certificates_released',
            field=models.BooleanField(default=False, help_text='Tick to let attendees download their Certificate of Participation. Leave off until the conference has ended and the committee has approved release.'),
        ),
        migrations.CreateModel(
            name='ConferenceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, editable=False, help_text='Public reference printed on the certificate and used to verify it.', max_length=40, null=True, unique=True)),
                ('participant_name', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False, help_text='Tick to invalidate this certificate. Verification will report it as revoked.')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='membership.eltanconferenceregistration')),
            ],
            options={
                'verbose_name': 'Conference Certificate',
                'verbose_name_plural': 'Conference Certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
